<?php

namespace Database\Seeders\Opciones;

use App\Models\Opcion;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class materno_perinatal extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Opcion::create(["ref_campo" => "ma_aceptacion_embarazo", "pregunta_opcion" => "SI", "valor" => "3"]);
//Opcion::create(["ref_campo" => "ma_fecha_control_prenatal", "pregunta_opcion" => "Control prenatal (ingresar dato)", "valor" => "0"]);
//Opcion::create(["ref_campo" => "ma_fecha_ultima_regla", "pregunta_opcion" => "Fecha de la ultima regla", "valor" => "0"]);
//Opcion::create(["ref_campo" => "ma_fecha_parto", "pregunta_opcion" => "Fecha probable del parto", "valor" => "0"]);
//Opcion::create(["ref_campo" => "ma_ganancia_peso", "pregunta_opcion" => "Ganancia de peso (ingresar dato)", "valor" => "0"]);
//Opcion::create(["ref_campo" => "ma_gestacion", "pregunta_opcion" => "Gestación (ingresar dato)", "valor" => "0"]);
Opcion::create(["ref_campo" => "ma_carnet", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_carnet", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_prenatal_mensual", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_prenatal_mensual", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_examen_serologia_1_trimestre", "pregunta_opcion" => "NO", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_serologia_1_trimestre", "pregunta_opcion" => "Positivo", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_serologia_1_trimestre", "pregunta_opcion" => "Negativo", "valor" => "0"]);
Opcion::create(["ref_campo" => "ma_examen_serologia_2_trimestre", "pregunta_opcion" => "NO", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_serologia_2_trimestre", "pregunta_opcion" => "Positivo", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_serologia_2_trimestre", "pregunta_opcion" => "Negativo", "valor" => "0"]);
Opcion::create(["ref_campo" => "ma_examen_serologia_3_trimestre", "pregunta_opcion" => "NO", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_serologia_3_trimestre", "pregunta_opcion" => "Positivo", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_serologia_3_trimestre", "pregunta_opcion" => "Negativo", "valor" => "0"]);
Opcion::create(["ref_campo" => "ma_examen_vih_1_trimestre", "pregunta_opcion" => "NO", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_vih_1_trimestre", "pregunta_opcion" => "Positivo", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_vih_1_trimestre", "pregunta_opcion" => "Negativo", "valor" => "0"]);
Opcion::create(["ref_campo" => "ma_examen_vih_2_trimestre", "pregunta_opcion" => "NO", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_vih_2_trimestre", "pregunta_opcion" => "Positivo", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_vih_2_trimestre", "pregunta_opcion" => "Negativo", "valor" => "0"]);
Opcion::create(["ref_campo" => "ma_examen_vih_3_trimestre", "pregunta_opcion" => "NO", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_vih_3_trimestre", "pregunta_opcion" => "Positivo", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_examen_vih_3_trimestre", "pregunta_opcion" => "Negativo", "valor" => "0"]);
Opcion::create(["ref_campo" => "ma_odontologico", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_odontologico", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_suplementacion", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_suplementacion", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_sedentarismo", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_sedentarismo", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_bebidas_alcoholicas", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_bebidas_alcoholicas", "pregunta_opcion" => "SI", "valor" => "3"]);
//Opcion::create(["ref_campo" => "ma_fecha_ultimo_parto", "pregunta_opcion" => "Fecha del último parto", "valor" => ""]);
Opcion::create(["ref_campo" => "ma_depresion_postparto", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_depresion_postparto", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_institucional", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_institucional", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_aborto_no_especificado", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_aborto_no_especificado", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_hemorragia_precoz", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_hemorragia_precoz", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_hemorragia_anteparto", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_hemorragia_anteparto", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_hipertension", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_hipertension", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_vomitos", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_vomitos", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_madre", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_madre", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_diabetes_mellitus", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_diabetes_mellitus", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_hallazgo_anormal", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_hallazgo_anormal", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_parto_unico", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_parto_unico", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_parto_complicado", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_parto_complicado", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_hemorragia_postparto", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_hemorragia_postparto", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_parto_cesarea", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_parto_cesarea", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_otras_complicaciones_parto", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_otras_complicaciones_parto", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_otras_complicaciones_purperio", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_otras_complicaciones_purperio", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_hospitalizacion_sifilis", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_hospitalizacion_sifilis", "pregunta_opcion" => "SI", "valor" => "3"]);
//Opcion::create(["ref_campo" => "ma_edad_gestacional", "pregunta_opcion" => "Ingresar dato", "valor" => ""]);
Opcion::create(["ref_campo" => "ma_plan_canguro", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_plan_canguro", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_curso_maternidad_paternidad", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_curso_maternidad_paternidad", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_medica", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_medica", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_enfermeria", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_enfermeria", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_odontologica", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_odontologica", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_antigeno_hepatitis_b", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_antigeno_hepatitis_b", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_cancer_cuello_uterino", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_cancer_cuello_uterino", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_glicemia_ayuna", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_glicemia_ayuna", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_hemoclasificacion", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_hemoclasificacion", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_hemograma", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_hemograma", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_hemoparasitos_chagas", "pregunta_opcion" => "NO", "valor" => "5"]);
Opcion::create(["ref_campo" => "ma_hemoparasitos_chagas", "pregunta_opcion" => "Positivo", "valor" => "40"]);
Opcion::create(["ref_campo" => "ma_hemoparasitos_chagas", "pregunta_opcion" => "Negativo", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_toxoplasma", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_toxoplasma", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_rubeola", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_rubeola", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_varicela", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_varicela", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_prueba_treponemica_sifilis", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_prueba_treponemica_sifilis", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_urocultivo", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_urocultivo", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_prueba_vih", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_prueba_vih", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_espermograma", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_espermograma", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_citologia", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_citologia", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_elisa", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_elisa", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_micronutrientes", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_micronutrientes", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_prenatal_medica_general", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_prenatal_medica_general", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_prenatal_enfermeria", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_prenatal_enfermeria", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_prenatal_medica_obstetra", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_prenatal_medica_obstetra", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_prenatal_consulta_nutricion", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_prenatal_consulta_nutricion", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_vacunacion_toxoide", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_vacunacion_toxoide", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_vacunacion_difteria", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_vacunacion_difteria", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_vacunacion_tosferina", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_vacunacion_tosferina", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_vacunacion_influenza", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_vacunacion_influenza", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_ecografia_obstetrica", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_ecografia_obstetrica", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_ecografia_anatomico", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_ecografia_anatomico", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_interrupcion_voluntaria_embarazo", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_interrupcion_voluntaria_embarazo", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_asesoria_anticonceptiva_ive", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_asesoria_anticonceptiva_ive", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_purperio", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_purperio", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_pediatria", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_pediatria", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_atencion_recien_nacido", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_atencion_recien_nacido", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_hemograma_recien_nacido", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_hemograma_recien_nacido", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_hemoclasificacion_recien_nacido", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_hemoclasificacion_recien_nacido", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_sifilis_recien_nacido", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_sifilis_recien_nacido", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_vih_recien_nacido", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_vih_recien_nacido", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_chagas_recien_nacido", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_chagas_recien_nacido", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_tsh_recien_nacido", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_tsh_recien_nacido", "pregunta_opcion" => "SI", "valor" => "3"]);
Opcion::create(["ref_campo" => "ma_tamizaje_genetico_recien_nacido", "pregunta_opcion" => "NO", "valor" => "1"]);
Opcion::create(["ref_campo" => "ma_tamizaje_genetico_recien_nacido", "pregunta_opcion" => "SI", "valor" => "3"]);

    }
}
